version: '3.9'

services:
  ubuntu:
    image: "wordpress-react"
    volumes:
      - ./public/wordpress:/var/www/html
    ports:
      - 80:80
    depends_on:
      - php
      - db

  db:
    image: mariadb:10.4
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
